pipeline {
	agent any
    parameters {
		string(name: 'BROWSER', defaultValue: 'chrome', description: 'Выберите браузер (chrome/firefox)')
    }
    stages {
		stage('Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/PetFactory1991/JavaSelenideJenkinsAllureDockerSelenoid.git'
            }
        }
        stage('Run Tests') {
			steps {
				sh "/opt/homebrew/bin/mvn clean test -Dbrowser=${params.BROWSER} -Dremote=http://165.22.93.142:4444/wd/hub"
            }
        }
        stage('Generate Allure Report') {
			steps {
				sh '/opt/homebrew/bin/allure generate allure-results -o allure-report --clean'
    		}
		}
    }
    post {
		always {
			allure includeProperties: false, results: [[path: "allure-results"]]
        }
    }
}

